# Generated by Django 4.0.4 on 2022-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('1', 'ICE'), ('2', 'IF'), ('3', 'SIRET')], default='1', max_length=1),
        ),
    ]
