# Generated by Django 4.0.4 on 2022-08-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer',
            new_name='customer_detail',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
