# Generated by Django 4.0.4 on 2022-08-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModelInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.TextField(default='')),
                ('designation', models.TextField(default='')),
                ('prix', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.TextField(default='')),
                ('total_price', models.FloatField(default=0)),
                ('tva', models.FloatField(default=0)),
                ('ttc', models.FloatField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
                ('file_name', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('basemodelinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturation.basemodelinvoice')),
                ('status', models.TextField(choices=[('1', 'En cours'), ('2', 'Validé'), ('3', 'non validé')], default='1', max_length=1)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('remainder_date', models.DateField(default='')),
            ],
            bases=('facturation.basemodelinvoice',),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('basemodelinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturation.basemodelinvoice')),
                ('status', models.TextField(choices=[('1', 'Payé'), ('2', 'Non payé')], default='2', max_length=1)),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateField(default='')),
            ],
            bases=('facturation.basemodelinvoice',),
        ),
    ]
