# Generated by Django 4.0.4 on 2022-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_basemodelinvoice_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodelinvoice',
            name='file_name',
        ),
        migrations.AddField(
            model_name='devis',
            name='devis_docx',
            field=models.FileField(blank=True, null=True, upload_to='devis/docx/'),
        ),
        migrations.AddField(
            model_name='devis',
            name='devis_pdf',
            field=models.FileField(blank=True, null=True, upload_to='devis/pdf/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_docx',
            field=models.FileField(blank=True, null=True, upload_to='factures/docx/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/pdf/'),
        ),
    ]
