# Generated by Django 4.0.4 on 2022-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_remove_basemodelinvoice_file_name_devis_devis_docx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='devis_docx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='devis_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_docx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
