# Generated by Django 4.0.4 on 2022-08-17 13:33

from django.db import migrations, models
import facturation.models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_alter_devis_devis_docx_alter_devis_devis_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodelinvoice',
            name='remider_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devis',
            name='devis_docx',
            field=models.FileField(blank=True, null=True, upload_to=facturation.models.devis_upload_path),
        ),
        migrations.AlterField(
            model_name='devis',
            name='devis_pdf',
            field=models.FileField(blank=True, null=True, upload_to=facturation.models.devis_upload_path),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_docx',
            field=models.FileField(blank=True, null=True, upload_to=facturation.models.facturation_upload_path),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to=facturation.models.facturation_upload_path),
        ),
    ]
